Improve logging
- Write a decorator for logging
- Drop off logging datetime as Systemd already does it
- Comply with Systemd priority STDOUT syntax
- Use printf instead of echo

diff --git a/arb b/arb
--- a/arb
+++ b/arb
@@ -5,15 +5,17 @@
 # TODO: Automatically create unmount all dirs at /run/user/$uid/arb/ 
 umountCrypt() { # args: $mount
 # Unmount a Gocryptfs directory 
-	([ -d "$1" ] && fusermount -uz "$1") || (echo "$(date +"[%b %d %H:%M:%S]") error: unmounting $1 failed"; return 1)
+	([ -d "$1" ] && fusermount -uz "$1") || (printf "<3>ERROR: %s\n" "unmounting $1 failed"; return 1)
 	[ -n "$(ls -A "$1")" ] || rm -r "$1" # remove dir if empty
 }
 
 # TODO: Automatically create a mount at /run/user/$uid/arb/repo_name 
 mountCrypt() { # args: $src $mount_point $pass $exclude(opt)
 # Mount a Gocryptfs directory
-	[ -d "$2" ] && [[ -n "$(ls -A "$2")" ]] && (echo "$(date +"[%b %d %H:%M:%S]") warning: $2 is already mounted, unmounting..."; (umountCrypt "$2" && sleep 2) || return 1) # unmount if already mounted
-	mkdir -p "$2" # make dir if inexistent
+	[ -d "$2" ] && [[ -n "$(ls -A "$2")" ]] &&
+    (printf "<4>WARNING: %s\n" "$2 is already mounted, unmounting..."; (umountCrypt "$2" && sleep 2) || return 1) # unmount if already mounted
+	# FIXME: Use IF instead of branching
+    mkdir -p "$2" # make dir if inexistent
 	if [ "$4" ]; then # mount reverse encrypted
 		gocryptfs -extpass pass -extpass "$3" -exclude-from "$4" -reverse "$1" "$2"
 	else
@@ -28,7 +30,7 @@ syncDisk() { #args: $src $dst
 
 syncCloud() { # syncCloud $name $src $stream
 # Sync a dir to a cloud bucket
-	echo "$(date +"[%b %d %H:%M:%S]") sync: syncing $1 to $3"
+	printf "<5>NOTICE: %s\n" "syncing $1 to $3"
 	#rclone sync -u --use-server-modtime --skip-links --fast-list --max-backlog=-1 "$2/" "$3:$1/"
 	rclone sync -u --use-server-modtime --skip-links --fast-list -v "$2/" "$3:$1/"
 }
@@ -63,26 +65,50 @@ archiveBorgLite() { # $borg_repo $borg_exclude $src $borg_pass(opt) $borg_key(op
 	borg prune --list --keep-last=1 # purge old
 }
 
+# Decorate
+decorate() { # args: function
+# Decorator for logging
+    eval "
+        _inner_$(typeset -f "$1")
+        $1"'() {
+            printf >&2 "<5>NOTICE: %s\n" "'$1' started"
+            _inner_'$1' "$@"
+            local ret=$?
+            printf >&2 "<5>NOTICE: %s\n" "'$1' ended with status $ret"
+            return "$ret"
+        }'
+}
+
 # MAIN
-for pid in $(pidof -x arb); do # exit if already being executed
+# Exit without doing anything if already being executed
+for pid in $(pidof -x arb); do 
     if [ "$pid" != $$ ]; then
-	    echo "$(date +"[%b %d %H:%M:%S]") error: program is already running with PID $pid"
+	    printf "<3>ERROR: %s\n" "program is already running with PID '"$pid"'!"
         exit 1
     fi
 done
 
-trap ctrl_c INT # clean exit with ctrl+c
+# Trap ^C to allow forceful exit from child
+trap ctrl_c INT 
 ctrl_c() {
     kill -15 "$child" && wait "$child" # send SIGTERM to child process
     [ "$mount" ] && umountCrypt "$mount" # unmount last mount point
-    echo -e "\n$(date +"[%b %d %H:%M:%S]") error: program was manually terminated" && exit 1
+    printf "<3>ERROR: %s\n" "program with PID '"$child"' was manually terminated!"
+    exit 1
 }
 
-config="$HOME/.config/arb/config"
+# Decorete functions with logging
+decorate syncDisk
+decorate syncCloud
+decorate archiveSys
+decorate archiveBorg
+decorate archiveBorgLite
 
+# Source variables and commands from config file
+config="$HOME/.config/arb/config"
 if [ -f "$config" ]; then # exit with config not found
     source "$config"
 else
-    echo -e "\n$(date +"[%b %d %H:%M:%S]"): config file not found!" && exit 1
+    printf "<3>ERROR: %s\n" "config file not found!"
+    exit 1
 fi
-
