feat: improve log formatting
Log properly formatted messages for terminal stdout and systemd.

diff --git a/arbie b/arbie
--- a/arbie
+++ b/arbie
@@ -7,6 +7,51 @@
 # @usage: arbie
 # @deps: borg, gocryptfs, rclone, rsync, git, gopass | pass
 
+# shellcheck disable=2034,2059
+
+# UTILS
+# -----
+# Log format strings
+if [ "$TERM" == "dumb" ]; then # is it running under systemd?
+  emerg="<0>%s\n" # red
+  alert="<1>%s\n"
+  crit="<2>%s\n"
+  err="<3>%s\n"
+  warning="<4>%s\n" # yellow
+  notice="<5>%s\n" # white
+  info="<6>%s\n"
+  debug="<7>%s\n" # muted 
+
+else
+  reset="\e[0;0m"
+  strong="\e[1;0m"
+  muted="\e[1;30m"
+  red="\e[1;31m"
+  yellow="\e[1;33m"
+
+  emerg="${red}EMERGENCY: %s${reset}\n"
+  alert="${red}ALERT: %s${reset}\n"
+  crit="${red}CRITICAL: %s${reset}\n"
+  error="${red}ERROR: %s${reset}\n"
+  warning="${yellow}WARNING: %s${reset}\n"
+  notice="${strong}NOTICE: %s${reset}\n"
+  info="INFO: %s\n"
+  debug="${muted}DEBUG: %s${reset}\n"
+fi
+
+# Function log decorator
+_decorate() {
+  # shellcheck disable=2086
+  eval "_inner_$(typeset -f "$1")
+  $1"'() {
+    printf >&2 "$notice" "'$1' started"
+    _inner_'$1' "$@"
+    local ret=$?
+    printf >&2 "$notice" "'$1' ended with status $ret"
+    return "$ret"
+  }'
+}
+
 # ENV
 # ---
 # Debug
@@ -16,7 +61,7 @@
 # Check if already being executed
 for pid in $(pidof -x arbie); do
   if [ "$pid" != $$ ]; then
-    printf "<3>ERROR: %s\n" "program is already running with PID '$pid'!"
+    printf "$err" "Program is already running with PID '$pid'"
     exit 1
   fi
 done
@@ -25,7 +70,7 @@ done
 deps=(borg gocryptfs rclone rsync git)
 for dep in "${deps[@]}"; do
   if ! [[ $(command -v "$dep") ]]; then
-    printf "<3>ERROR: %s\n" "$dep not found. Missing required!" && exit 1
+    printf "$err" "$dep not found" && exit 1
   fi
 done
 
@@ -34,7 +79,7 @@ pass_bin=$(command -v gopass) # gopass by default
 pass_bin=${pass_bin:-$(command -v pass)} # pass as fallback
 
 if ! [ "$pass_bin" ]; then # exit if none
-  printf "<3>ERROR: %s\n" "gopass or pass not found. Missing required!" && exit 1
+  printf "$err" "Gopass or pass not found" && exit 1
 fi
 
 # Check config file
@@ -45,7 +90,7 @@ else
 fi
 
 if ! [ -f "$config" ]; then
-  printf "<3>ERROR: %s\n" "config file not found! Templates can be found at /usr/share/arbie" && exit 1
+  printf "$err" "Config file not found, templates at '/usr/share/arbie/'" && exit 1
 fi
 
 # Set temporary dir 
@@ -53,37 +98,23 @@ tmp="/run/user/$(id -u)/arbie" # for systems with systemd
 
 # LIB
 # ---
-# Logging decorator
-# TODO: Check for env and decorate w/ colors when not invoked by systemd.
-_decorate() {
-# shellcheck disable=2086
-  eval "_inner_$(typeset -f "$1")
-  $1"'() {
-    printf >&2 "<5>NOTICE: %s\n" "'$1' started"
-    _inner_'$1' "$@"
-    local ret=$?
-    printf >&2 "<5>NOTICE: %s\n" "'$1' ended with status $ret"
-    return "$ret"
-  }'
-}
-
 # Unmount a Gocryptfs file system 
 umountCrypt() {
   local OPTIND name mount
   while getopts "n:" opt; do
     case $opt in
       n) name=$OPTARG;;
-      *) printf "<3>ERROR: %s\n" "Something is wrong!";;
+      *) printf "$err" "${FUNCNAME[0]}: invalid arguments";;
     esac
   done
 
   if ! [ "$name" ]; then
-    printf "<3>ERROR: %s\n" "Missing required arguments!" && return 1
+    printf "$err" "${FUNCNAME[0]}: missing required arguments" && return 1
   fi
 
   mount="$tmp/$name"
   ([ -d "$mount" ] && fusermount -uz "$mount") || # try to unmount if it exists
-  (printf "<3>ERROR: %s\n" "unmounting $name failed"; return 1) # print and return error if it fails
+  (printf "$err" "${FUNCNAME[0]}: Failed to unmount $name"; return 1) # print and return error if it fails
   [ -n "$(find "$mount" -maxdepth 0 -type d -empty 2>/dev/null)" ] && rm -r "$mount" # remove dir if empty
 }
 
@@ -96,22 +127,22 @@ mountCrypt() {
       i) input=$OPTARG;;
       p) pass=$OPTARG;;
       e) exclude_file=$OPTARG;; #optional
-      *) printf "<3>ERROR: %s\n" "Something is wrong!";;
+      *) printf "$err" "${FUNCNAME[0]}: invalid arguments";;
     esac
   done
 
   if ! [ "$name" ] && [ "$input" ] && [ "$pass" ]; then
-    printf "<3>ERROR: %s\n" "Missing required arguments!" && return 1
+    printf "$err" "${FUNCNAME[0]}: missing required arguments" && return 1
   fi
 
   mount="$tmp/$name"
   if [ -d "$mount" ] && [ -z "$(find "$mount" -maxdepth 0 -type d -empty 2>/dev/null)" ]; then # if mount exists and is not empty
-    printf "<4>WARNING: %s\n" "$name is already mounted, unmounting..."
+    printf "$warning" "${FUNCNAME[0]}: $name is already mounted, unmounting..."
     (umountCrypt -n "$name" && sleep 2) || return 1 # unmount if already mounted
   fi
 
   if ! [ -d "$input" ]; then # check if input dir exists
-    printf "<3>ERROR: %s\n" "$input does not exist!" && return 1
+    printf "$err" "${FUNCNAME[0]}: $input does not exist" && return 1
   fi
 
   mkdir -p "$mount" # create mountpoint dir if inexistent
@@ -126,12 +157,12 @@ syncDisk() {
       n) name=$OPTARG;;
       i) input=$OPTARG;; # optional
       o) output=$OPTARG;;
-      *) printf "<3>ERROR: %s\n" "Something is wrong!";;
+      *) printf "$err" "${FUNCNAME[1]}: invalid arguments";;
     esac
   done
 
   if ! [ "$name" ] && [ "$output" ]; then
-    printf "<3>ERROR: %s\n" "Missing required arguments!" && return 1
+    printf "$err" "${FUNCNAME[1]}: missing required arguments" && return 1
   fi
 
 	rsync -a --delete "${input:-$tmp/$name}/" "$output/" # assign value to $input with not set
@@ -145,17 +176,17 @@ syncCloud() {
       n) name=$OPTARG;;
       i) input=$OPTARG;; # optional
       s) read -r -a streams <<< "$OPTARG";;
-      *) printf "<3>ERROR: %s\n" "Something is wrong!";;
+      *) printf "$err" "${FUNCNAME[1]}: invalid arguments";;
     esac
   done
 
   # shellcheck disable=2128
   if ! [ "$name" ] && [ "$streams" ]; then
-    printf "<3>ERROR: %s\n" "Missing required arguments!" && return 1
+    printf "$err" "${FUNCNAME[1]}: missing required arguments" && return 1
   fi
 
   for stream in "${streams[@]}"; do
-    printf "<5>NOTICE: %s\n" "syncing $name to $stream"
+    printf "$notice" "${FUNCNAME[1]}: syncing $name to $stream"
     rclone sync -u --use-server-modtime --skip-links --fast-list --max-backlog=-1 \
     "${input:-$tmp/$name}/" "$stream:$name/" # assign value to $input with not set
   done
@@ -169,12 +200,12 @@ archiveSys() {
     case $opt in
       o) output=$OPTARG;;
       e) exclude=$OPTARG;;
-      *) printf "<3>ERROR: %s\n" "Something is wrong!";;
+      *) printf "$err" "${FUNCNAME[1]}: invalid arguments";;
     esac
   done
 
   if ! [ "$output" ] && [ "$exclude" ]; then
-    printf "<3>ERROR: %s\n" "Missing required arguments!" && return 1
+    printf "$err" "${FUNCNAME[1]}: missing required arguments" && return 1
   fi
 
 	mkdir -p "$output" # make dir if inexistent
@@ -196,12 +227,12 @@ archiveBorg() {
       p) pass=$OPTARG && export BORG_PASSCOMMAND="$pass_bin $pass";; # optional
       k) key=$OPTARG && export BORG_KEY_FILE="$key";; # optional
       l) lite=1;; # optional
-      *) printf "<3>ERROR: %s\n" "Something is wrong!";;
+      *) printf "$err" "${FUNCNAME[1]}: invalid arguments";;
     esac
   done
 
   if ! [ "$name" ] && [ "$input" ] && [ "$output" ] && [ "$exclude_file" ]; then
-    printf "<3>ERROR: %s\n" "Missing required arguments!" && return 1
+    printf "$err" "${FUNCNAME[1]}: missing required arguments" && return 1
   fi
 
   if ! [ $lite ]; then # default
@@ -219,18 +250,20 @@ archiveBorg() {
 # MAIN
 # ----
 # Trap ^C to allow forceful exit from child
-trap _ctrl_c INT # FIXME: Shouldn't this be bellow the func declaration?
+trap _ctrl_c INT
+
 _ctrl_c() {
-  kill -15 $! && sleep 5 && sync # send SIGTERM to child process
+  pid=$!
+  kill -15 $pid && sleep 5 && sync # send SIGTERM to child process
 
   # loop through existent dirs and try to umount/rm them
   mapfile -t mounts < <(fd --type d --max-depth 1 --base-directory "$tmp")
   for name in "${mounts[@]}"; do
-      umountCrypt -n "$name"
+    umountCrypt -n "$name"
   done
 
   [ "$mount" ] && umountCrypt -n "$mount" # unmount last mount point
-  printf "<3>ERROR: %s\n" "program with PID '$!' was manually terminated!"
+  printf "$err" "program with PID '$pid' was manually terminated!"
   exit 1
 }
 
