refactor: organize and document

diff --git a/arbie b/arbie
--- a/arbie
+++ b/arbie
@@ -1,43 +1,73 @@
 #!/usr/bin/env bash
 #
-# Automatic Robust Backup
+# Arbie: Automatic Robust Backup
 #
 # @author: Daniel Souza <me@posix.dev.br>
 # @license: MIT
+# @usage: arbie
+# @deps: borg, gocryptfs, rclone, rsync, git, gopass | pass
 
-# Debugging
-# set -e # exit when anything 'fails'
-# use ||: at end of line to ignore errors
+# ENV
+# ---
+# Debug
+# set -e # exit when a error is returned
+# use ||: at EOL to ignore errors
 
-# Check for dependencies
-deps=(borg gocryptfs rclone rsync git)
-for dep in "${deps[@]}"; do
-  if ! [[ $(command -v "$dep") ]]; then
-      printf "<3>ERROR: %s\n" "$dep not found. Missing required!" && exit 1
+# Check if already being executed
+for pid in $(pidof -x arbie); do
+  if [ "$pid" != $$ ]; then
+    printf "<3>ERROR: %s\n" "program is already running with PID '$pid'!"
+    exit 1
   fi
 done
 
-pass_bin=$(command -v gopass) # check for gopass
-pass_bin=${pass_bin:-$(command -v pass)} # fallback for pass
+# Check dependencies
+deps=(borg gocryptfs rclone rsync git)
+for dep in "${deps[@]}"; do
+  if ! [[ $(command -v "$dep") ]]; then
+    printf "<3>ERROR: %s\n" "$dep not found. Missing required!" && exit 1
+  fi
+done
+
+# Check password manager
+pass_bin=$(command -v gopass) # gopass by default
+pass_bin=${pass_bin:-$(command -v pass)} # pass as fallback
+
 if ! [ "$pass_bin" ]; then # exit if none
   printf "<3>ERROR: %s\n" "gopass or pass not found. Missing required!" && exit 1
 fi
 
-# Check for config file
+# Check config file
 if [ "$XDG_CONFIG_HOME" ]; then
   config="$XDG_CONFIG_HOME/arbie/arbie.conf"
 else
   config="$HOME/config/arbie/arbie.conf"
 fi
 
-if ! [ -f "$config" ]; then # exit with config not found
+if ! [ -f "$config" ]; then
   printf "<3>ERROR: %s\n" "config file not found! Templates can be found at /usr/share/arbie" && exit 1
 fi
 
-# Dir for temporary stuff
-tmp=/run/user/$(id -u)/arbie
+# Set temporary dir 
+tmp="/run/user/$(id -u)/arbie" # for systems with systemd
 
-# Unmount a Gocryptfs directory
+# LIB
+# ---
+# Logging decorator
+# TODO: Check for env and decorate w/ colors when not invoked by systemd.
+_decorate() {
+# shellcheck disable=2086
+  eval "_inner_$(typeset -f "$1")
+  $1"'() {
+    printf >&2 "<5>NOTICE: %s\n" "'$1' started"
+    _inner_'$1' "$@"
+    local ret=$?
+    printf >&2 "<5>NOTICE: %s\n" "'$1' ended with status $ret"
+    return "$ret"
+  }'
+}
+
+# Unmount a Gocryptfs file system 
 umountCrypt() {
   local OPTIND name mount
   while getopts "n:" opt; do
@@ -57,7 +87,7 @@ umountCrypt() {
   [ -n "$(find "$mount" -maxdepth 0 -type d -empty 2>/dev/null)" ] && rm -r "$mount" # remove dir if empty
 }
 
-# Mount a Gocryptfs directory
+# Mount a Gocryptfs file system 
 mountCrypt() {
   local OPTIND name input pass exclude_file mount
   while getopts "n:i:p:e:" opt; do
@@ -88,7 +118,7 @@ mountCrypt() {
   gocryptfs -extpass "$pass_bin" -extpass "$pass" ${exclude_file:+-exclude-from "$exclude_file"} -reverse "$input" "$mount"
 }
 
-# Sync a dir to disk
+# Sync a directory to disk
 syncDisk() {
   local OPTIND name input output
   while getopts "n:i:o:" opt; do
@@ -107,7 +137,7 @@ syncDisk() {
 	rsync -a --delete "${input:-$tmp/$name}/" "$output/" # assign value to $input with not set
 }
 
-# Sync a dir to a cloud bucket
+# Sync a directory to a rclone bucket
 syncCloud() {
   local OPTIND name input streams
   while getopts "n:i:s:" opt; do
@@ -119,7 +149,7 @@ syncCloud() {
     esac
   done
 
-  # shellcheck disable=SC2128
+  # shellcheck disable=2128
   if ! [ "$name" ] && [ "$streams" ]; then
     printf "<3>ERROR: %s\n" "Missing required arguments!" && return 1
   fi
@@ -131,7 +161,7 @@ syncCloud() {
   done
 }
 
-# Archive system confs
+# Archive system configs (pkg list & /etc)
 archiveSys() {
   local OPTIND name output exclude
   name="sys"
@@ -154,7 +184,7 @@ archiveSys() {
   (git -C "$output" add -A && git -C "$output" commit -m "$(date +%Y-%m-%d)") ||: # archive changes in git
 }
 
-# Archive a dir with borg (default)
+# Archive a directory with Borg
 archiveBorg() {
   local OPTIND name input output exclude_file pass key lite
   while getopts "n:i:o:e:p:k:l" opt; do
@@ -186,31 +216,10 @@ archiveBorg() {
   fi
 }
 
-# Logging decorator
-# TODO: Check for env and decorate w/ colors when not invoked by systemd.
-_decorate() {
-# shellcheck disable=2086
-  eval "_inner_$(typeset -f "$1")
-  $1"'() {
-    printf >&2 "<5>NOTICE: %s\n" "'$1' started"
-    _inner_'$1' "$@"
-    local ret=$?
-    printf >&2 "<5>NOTICE: %s\n" "'$1' ended with status $ret"
-    return "$ret"
-  }'
-}
-
 # MAIN
-# Exit without doing anything if already being executed
-for pid in $(pidof -x arbie); do
-  if [ "$pid" != $$ ]; then
-    printf "<3>ERROR: %s\n" "program is already running with PID '$pid'!"
-    exit 1
-  fi
-done
-
+# ----
 # Trap ^C to allow forceful exit from child
-trap _ctrl_c INT
+trap _ctrl_c INT # FIXME: Shouldn't this be bellow the func declaration?
 _ctrl_c() {
   kill -15 $! && sleep 5 && sync # send SIGTERM to child process
 
