Fix bug with 'pass' checking procedure

diff --git a/arbie b/arbie
--- a/arbie
+++ b/arbie
@@ -17,9 +17,11 @@ for dep in "${deps[@]}"; do
     fi
 done
 
-pass_bin=$(command -v pass)
+pass_bin=$(command -v pass) # check for pass
 pass_bin=${pass_bin:-$(command -v pass)} # prefer gopass
-[ "$pass_bin" ] || printf "<3>ERROR: %s\n" "gopass or pass not found. Missing required!" && exit 1
+if ! [ "$pass_bin" ]; then # exit if no alternative is found
+    printf "<3>ERROR: %s\n" "gopass or pass not found. Missing required!" && exit 1
+fi
 
 # Check for config file
 config="$XDG_CONFIG_HOME/arbie/arbie.conf"
diff --git a/vaultguard b/vaultguard
--- a/vaultguard
+++ b/vaultguard
@@ -24,9 +24,11 @@ fi
 
 # Check if pass or gopass is installed
 
-pass_bin=$(command -v pass)
+pass_bin=$(command -v pass) # check for pass
 pass_bin=${pass_bin:-$(command -v pass)} # prefer gopass
-[ "$pass_bin" ] || printf "ERROR: %s\n" "gopass or pass not found. Missing required!" && exit 1
+if ! [ "$pass_bin" ]; then # exit if no alternative is found
+    printf "<3>ERROR: %s\n" "gopass or pass not found. Missing required!" && exit 1
+fi
 
 _unlock() {
     if [ -z "$( ls -A "$dst" )" ]; then
