Workaround for Bash
Command subsitution as the first term of a parameter expansion
work with Zsh but not with Bash.

diff --git a/arbie b/arbie
--- a/arbie
+++ b/arbie
@@ -17,8 +17,9 @@ for dep in "${deps[@]}"; do
     fi
 done
 
-pass_bin=${$(command -v pass):-$(command -v pass)} # prefer gopass
-[ $pass_bin ] || printf "<3>ERROR: %s\n" "gopass or pass not found. Missing required!" && exit 1
+pass_bin=$(command -v pass)
+pass_bin=${pass_bin:-$(command -v pass)} # prefer gopass
+[ "$pass_bin" ] || printf "<3>ERROR: %s\n" "gopass or pass not found. Missing required!" && exit 1
 
 # Check for config file
 config="$XDG_CONFIG_HOME/arbie/arbie.conf"
diff --git a/vaultguard b/vaultguard
--- a/vaultguard
+++ b/vaultguard
@@ -17,8 +17,10 @@ if [ -n "$(find "$src" -maxdepth 0 -type d -empty 2>/dev/null)" ]; then
 fi
 
 # Check if pass or gopass is installed
-pass_bin=${$(command -v pass):-$(command -v pass)} # prefer gopass
-[ $pass_bin ] || printf "ERROR: %s\n" "gopass or pass not found. Missing required!" && exit 1
+
+pass_bin=$(command -v pass)
+pass_bin=${pass_bin:-$(command -v pass)} # prefer gopass
+[ "$pass_bin" ] || printf "ERROR: %s\n" "gopass or pass not found. Missing required!" && exit 1
 
 _unlock() {
     if [ -z "$( ls -A "$dst" )" ]; then
